# ./docker-compose.yml

version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    image: pensiero/apache-php-mysql
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/public/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
